---
- name: Verbindungstest mit allen Ziel-VMs
  hosts: all
  gather_facts: no

  tasks:
    - name: Hostname anzeigen
      command: hostname
      register: result

    - name: Ausgabe des Hostnamens anzeigen
      debug:
        msg: "Hostname auf {{ inventory_hostname }}: {{ result.stdout }}"

